development: &non_production_settings
  site_url: http://www.study-languages-online.com
  site_name: Study Russian Online
  admin_email: dalles@inventos.ru
  support_email: support@study-languages-online.com
  gch_id: qweqwe
  gch_key: qweqwe



test:
  <<: *non_production_settings

production:
  site_url: http://www.study-languages-online.com
  site_name: Study Russian Online
  support_email: support@study-languages-online.com
  admin_email: dalles@inventos.ru
  gch_id: 736293013524833
  gch_key: -TfwjkzYrHfyvqMg_Qq-ZQ


